# Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

include:
  - compose.db.yaml # with db declared

services:
  server:
    container_name: server_free2top
    build:
      context: restApi
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./restApi/.env
    ports:
      - 4000:4000
    # Switch migration:run to migration:revert to revert the changes
    command: npm run typeorm migration:run -- -d ./src/data-source.ts
    
    # PostgreSQL database used by application. `depends_on` tells Docker Compose to
    # start the database before your application
    depends_on:
      db:
        condition: service_healthy
