# Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/
include:
  - compose.db.yaml # with db declared

services:
  server:
    container_name: server_free2top
    build:
      context: restApi
      dockerfile: Dockerfile
      target: dev
    env_file:
      - ./restApi/.env
    ports:
      - 4000:4000
    # Lauch service in dev mode with migration
    command: npm run dev-migration
    develop:
      # The watch attribute automatically updates and previews your running Compose services as you edit and save your code
      # Run docker compose up --watch to build and launch a Compose project and start the file watch mode
      watch:
        - action: sync
          path: ./restApi/src
          target: /usr/src/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./restApi/package.json

    # PostgreSQL database used by application. `depends_on` tells Docker Compose to
    # start the database before your application
    depends_on:
      db:
        condition: service_healthy

  client:
    container_name: client_free2top
    build:
      context: client
      dockerfile: Dockerfile
      target: dev
    command: npm run dev
    env_file:
      - ./client/.env
    ports:
      - 3000:3000
    develop:
      # The watch attribute automatically updates and previews your running Compose services as you edit and save your code
      # Run docker compose up --watch to build and launch a Compose project and start the file watch mode
      watch:
        - action: sync
          path: ./client/src
          target: /usr/src/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json
